server:
  port: 8083

spring:
  application:
    name: emergency-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: ems_user
    password: ems_password

management:
  endpoints:
    web:
      exposure:
        include: health,info

emergency:
  expiration:
    scheduler:
      fixed-delay-ms: 10000
