server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: ems_user
    password: ems_password

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    name: notification-service.log
